const movies = [
  {
    title: "Dune: Part Two",
    year: 2024,
    genre: "Sci-Fi",
    rating: 8.5,
    director: "Denis Villeneuve",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
  },
  {
    title: "Oppenheimer",
    year: 2023,
    genre: "Drama",
    rating: 8.9,
    director: "Christopher Nolan",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
  },
  {
    title: "Parasite",
    year: 2019,
    genre: "Thriller",
    rating: 8.5,
    director: "Bong Joon-ho",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  },
  {
    title: "The Batman",
    year: 2022,
    genre: "Action",
    rating: 7.8,
    director: "Matt Reeves",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
  },
  {
    title: "Interstellar",
    year: 2014,
    genre: "Sci-Fi",
    rating: 8.7,
    director: "Christopher Nolan",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  },
  {
    title: "The Godfather",
    year: 1972,
    genre: "Crime",
    rating: 9.2,
    director: "Francis Ford Coppola",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLegHnDmni69.jpg",
  },
  {
    title: "Blade Runner 2049",
    year: 2017,
    genre: "Sci-Fi",
    rating: 8.0,
    director: "Denis Villeneuve",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVmUC.jpg",
  },
  {
    title: "Whiplash",
    year: 2014,
    genre: "Drama",
    rating: 8.5,
    director: "Damien Chazelle",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
  },
  {
    title: "Mad Max: Fury Road",
    year: 2015,
    genre: "Action",
    rating: 8.1,
    director: "George Miller",
    poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    genre: "Crime",
    rating: 8.9,
    director: "Quentin Tarantino",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    genre: "Action",
    rating: 9.0,
    director: "Christopher Nolan",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  },
  {
    title: "Schindler's List",
    year: 1993,
    genre: "Drama",
    rating: 9.0,
    director: "Steven Spielberg",
    poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    genre: "Drama",
    rating: 9.3,
    director: "Frank Darabont",
    poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
  },
  {
    title: "Goodfellas",
    year: 1990,
    genre: "Crime",
    rating: 8.7,
    director: "Martin Scorsese",
    poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
  },
  {
    title: "Fight Club",
    year: 1999,
    genre: "Thriller",
    rating: 8.8,
    director: "David Fincher",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
  },
  {
    title: "Inception",
    year: 2010,
    genre: "Sci-Fi",
    rating: 8.8,
    director: "Christopher Nolan",
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
  },
  {
    title: "The Silence of the Lambs",
    year: 1991,
    genre: "Thriller",
    rating: 8.6,
    director: "Jonathan Demme",
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
  },
  {
    title: "Se7en",
    year: 1995,
    genre: "Thriller",
    rating: 8.6,
    director: "David Fincher",
    poster: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
  },
  {
    title: "The Matrix",
    year: 1999,
    genre: "Sci-Fi",
    rating: 8.7,
    director: "Lana & Lilly Wachowski",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  },
  {
    title: "Gladiator",
    year: 2000,
    genre: "Action",
    rating: 8.5,
    director: "Ridley Scott",
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
  },
  {
    title: "The Lion King",
    year: 1994,
    genre: "Animation",
    rating: 8.5,
    director: "Roger Allers",
    poster: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
  },
  {
    title: "Spirited Away",
    year: 2001,
    genre: "Animation",
    rating: 8.6,
    director: "Hayao Miyazaki",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
  },
  {
    title: "WALL·E",
    year: 2008,
    genre: "Animation",
    rating: 8.4,
    director: "Andrew Stanton",
    poster: "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
  },
  {
    title: "Avengers: Endgame",
    year: 2019,
    genre: "Action",
    rating: 8.4,
    director: "Anthony & Joe Russo",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  },
  {
    title: "Joker",
    year: 2019,
    genre: "Drama",
    rating: 8.4,
    director: "Todd Phillips",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  },
  {
    title: "1917",
    year: 2019,
    genre: "Drama",
    rating: 8.3,
    director: "Sam Mendes",
    poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
  },
  {
    title: "The Revenant",
    year: 2015,
    genre: "Drama",
    rating: 8.0,
    director: "Alejandro G. Iñárritu",
    poster: "https://image.tmdb.org/t/p/w500/ji3ecJphATlVgZNY98spFYMentI.jpg",
  },
  {
    title: "No Country for Old Men",
    year: 2007,
    genre: "Thriller",
    rating: 8.1,
    director: "Joel & Ethan Coen",
    poster: "https://image.tmdb.org/t/p/w500/6LWy0jvMpmjoS9fojNgHIKoWL05.jpg",
  },
  {
    title: "There Will Be Blood",
    year: 2007,
    genre: "Drama",
    rating: 8.2,
    director: "Paul Thomas Anderson",
    poster: "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
  },
  {
    title: "12 Angry Men",
    year: 1957,
    genre: "Drama",
    rating: 9.0,
    director: "Sidney Lumet",
    poster: "https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
  },
  {
    title: "Apocalypse Now",
    year: 1979,
    genre: "Drama",
    rating: 8.4,
    director: "Francis Ford Coppola",
    poster: "https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
  },
  {
    title: "Taxi Driver",
    year: 1976,
    genre: "Thriller",
    rating: 8.2,
    director: "Martin Scorsese",
    poster: "https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a2Opz4OB.jpg",
  },
  {
    title: "Alien",
    year: 1979,
    genre: "Sci-Fi",
    rating: 8.5,
    director: "Ridley Scott",
    poster: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
  },
  {
    title: "2001: A Space Odyssey",
    year: 1968,
    genre: "Sci-Fi",
    rating: 8.3,
    director: "Stanley Kubrick",
    poster: "https://image.tmdb.org/t/p/w500/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg",
  },
  {
    title: "A Clockwork Orange",
    year: 1971,
    genre: "Thriller",
    rating: 8.3,
    director: "Stanley Kubrick",
    poster: "https://image.tmdb.org/t/p/w500/4sHeTAp65WrSSuc05nRBKddhBxO.jpg",
  },
  {
    title: "Full Metal Jacket",
    year: 1987,
    genre: "Drama",
    rating: 8.3,
    director: "Stanley Kubrick",
    poster: "https://image.tmdb.org/t/p/w500/xUKPBBZjMBz4Ny1EZsE5pzJo7XK.jpg",
  },
  {
    title: "Saving Private Ryan",
    year: 1998,
    genre: "Drama",
    rating: 8.6,
    director: "Steven Spielberg",
    poster: "https://image.tmdb.org/t/p/w500/uqx37oZCLWa4GaGFGBfXKABfHcn.jpg",
  },
  {
    title: "Catch Me If You Can",
    year: 2002,
    genre: "Crime",
    rating: 8.1,
    director: "Steven Spielberg",
    poster: "https://image.tmdb.org/t/p/w500/whjxlnFMpHtvBh1UHaelZQJxNnV.jpg",
  },
  {
    title: "The Prestige",
    year: 2006,
    genre: "Thriller",
    rating: 8.5,
    director: "Christopher Nolan",
    poster: "https://image.tmdb.org/t/p/w500/tRNlZbgNCkfabsNs5GogbEKMkqA.jpg",
  },
  {
    title: "Memento",
    year: 2000,
    genre: "Thriller",
    rating: 8.4,
    director: "Christopher Nolan",
    poster: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
  },
  {
    title: "Gone Girl",
    year: 2014,
    genre: "Thriller",
    rating: 8.1,
    director: "David Fincher",
    poster: "https://image.tmdb.org/t/p/w500/ict5xFEIO2dBtMBtKET4vvPHVoe.jpg",
  },
  {
    title: "The Social Network",
    year: 2010,
    genre: "Drama",
    rating: 7.7,
    director: "David Fincher",
    poster: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHso.jpg",
  },
  {
    title: "La La Land",
    year: 2016,
    genre: "Drama",
    rating: 8.0,
    director: "Damien Chazelle",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  },
  {
    title: "Hereditary",
    year: 2018,
    genre: "Horror",
    rating: 7.3,
    director: "Ari Aster",
    poster: "https://image.tmdb.org/t/p/w500/p6wP4DKk0JpPTMaYi48oYxFDVQh.jpg",
  },
  {
    title: "Midsommar",
    year: 2019,
    genre: "Horror",
    rating: 7.1,
    director: "Ari Aster",
    poster: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
  },
  {
    title: "Get Out",
    year: 2017,
    genre: "Horror",
    rating: 7.7,
    director: "Jordan Peele",
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
  },
  {
    title: "Everything Everywhere",
    year: 2022,
    genre: "Sci-Fi",
    rating: 7.8,
    director: "Daniel Kwan & Daniel Scheinert",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
  },
  {
    title: "The Grand Budapest Hotel",
    year: 2014,
    genre: "Comedy",
    rating: 8.1,
    director: "Wes Anderson",
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
  },
  {
    title: "Knives Out",
    year: 2019,
    genre: "Comedy",
    rating: 7.9,
    director: "Rian Johnson",
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2wqWRdFjvObhFls.jpg",
  },
  {
    title: "Oldboy",
    year: 2003,
    genre: "Thriller",
    rating: 8.4,
    director: "Park Chan-wook",
    poster: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBmrr7GKCo.jpg",
  },
];

export default movies;
